### PR TITLE
Various Chrome/Firefox speedups

### PR DESCRIPTION
**Pull request by mattgodbolt**
Hi,

As discussed on email these are my changes.  Tested on Firefox 27.0.1 and Chrome 33 on Linux only.

I had to fix up the line-ending fixes to work for UNIX line endings.

Timings before/after on my 2.4GHz Core i5 laptop (fastest of 3 runs):
Before:
Firefox : 104ms. 26393.3 kB/s
Chrome :  634ms. 4329.5 kB/s

After:
Firefox : 83ms. 33071.2 kB/s
Chrome : Uncompressed cantrbry.zip in 52ms. 52786.7 kB/s

Usability:
To get best performance, the input data should be provided as a Uint8Array.  If it's passed as a string, it'll be converted to a Uint8Array.  To get binary data out as a Uint8Array, use readBinary(), which is fastest.  Else use read() (as before) to get a string out.

The simple test uses the string APIs throughout.  The performance test uses the binary, but also compares the string against the binary result when verifying.

My biggest concern is that this doesn't work on IE as I can't test it.

Hope it's useful!
- matt

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Closing after seven years and no reply :)

**Comment by emoller** [comment]
Wow... sorry Matt. I have no excuse other than that this repo has been very low key to say the least :)
Even if it has no users I owe it to your effort 7 years ago to make a PR to merge it. I will look at this on the weekend. Would you mind reopening the PR?

**Comment by opera-emoller** [comment]
Aaanyway... the commits were lost since you deleted your repo but I reconstructed them and pushed them seven years later. Thanks @mattgodbolt, maybe I should actually bring this little repo into 2021 :)

**Comment by mattgodbolt** [comment]
Oh bless you! And sorry I missed your reply (ironically haah!) I know how har dit is to keep on top of these things, so I appreciate all the work! Cheers, Matt :)

**Pull request closed without merging**
